create type gender AS ENUM ('FEMALE', 'MALE', 'NONBINARY');
create type zodiac_sign AS ENUM (
    'ARIES',
    'TAURUS',
    'GEMINI',
    'CANCER',
    'LEO',
    'VIRGO',
    'LIBRA',
    'SCORPIO',
    'SAGITTARIUS',
    'CAPRICORN',
    'AQUARIUS',
    'PISCES'
);

create table if not exists user_account (
    id bigint generated by default as identity primary key,
    email citext unique not null,
    password character varying not null,
    username citext unique not null,
    gender gender,
    birthday timestamp with time zone,
    location character varying,
    zodiac_sign zodiac_sign,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

DROP TRIGGER IF EXISTS user_account_insert ON user_account;
    CREATE TRIGGER user_account_insert BEFORE INSERT ON user_account FOR EACH ROW EXECUTE PROCEDURE create_timestamps();
DROP TRIGGER IF EXISTS user_account_update ON user_account;
    CREATE TRIGGER user_account_update BEFORE UPDATE ON user_account FOR EACH ROW EXECUTE PROCEDURE update_timestamps();

CREATE TABLE if not exists dream (
    id bigint generated by default as identity PRIMARY KEY,
    user_id bigint not null references user_account(id) on delete cascade,
    title character varying NOT NULL,
    description character varying NOT NULL,
    is_lucid boolean NOT NULL,
    is_nightmare boolean NOT NULL,
    is_recurring boolean NOT NULL,
    is_private boolean NOT NULL,
    is_starred boolean NOT NULL,
    emotions jsonb NOT NULL,
    dreamed_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

DROP TRIGGER IF EXISTS dream_insert ON dream;
    CREATE TRIGGER dream_insert BEFORE INSERT ON dream FOR EACH ROW EXECUTE PROCEDURE create_timestamps();
DROP TRIGGER IF EXISTS dream_update ON dream;
    CREATE TRIGGER dream_update BEFORE UPDATE ON dream FOR EACH ROW EXECUTE PROCEDURE update_timestamps();
